[2023-10-26T10:11:18.890+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrap_scryptopanic.run_selenium scheduled__2023-10-26T10:00:04.803573+00:00 [queued]>
[2023-10-26T10:11:19.565+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrap_scryptopanic.run_selenium scheduled__2023-10-26T10:00:04.803573+00:00 [queued]>
[2023-10-26T10:11:19.855+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-10-26T10:11:22.920+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_selenium> on 2023-10-26 10:00:04.803573+00:00
[2023-10-26T10:11:24.211+0000] {standard_task_runner.py:57} INFO - Started process 1835 to run task
[2023-10-26T10:11:25.248+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'scrap_scryptopanic', 'run_selenium', 'scheduled__2023-10-26T10:00:04.803573+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/scraping/cryptopanic.py', '--cfg-path', '/tmp/tmpmv6n5p4b']
[2023-10-26T10:11:26.592+0000] {standard_task_runner.py:85} INFO - Job 38: Subtask run_selenium
[2023-10-26T10:11:35.510+0000] {task_command.py:416} INFO - Running <TaskInstance: scrap_scryptopanic.run_selenium scheduled__2023-10-26T10:00:04.803573+00:00 [running]> on host 7b871cd064f6
[2023-10-26T10:11:40.179+0000] {abstractoperator.py:709} ERROR - Exception rendering Jinja template for task 'run_selenium', field 'bash_command'. Template: './start.sh'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 152, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-26T10:11:40.580+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1647, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2285, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1243, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 152, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-26T10:11:42.241+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=scrap_scryptopanic, task_id=run_selenium, execution_date=20231026T100004, start_date=20231026T101119, end_date=20231026T101142
[2023-10-26T10:11:42.706+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 38 for task run_selenium (./start.sh; 1835)
[2023-10-26T10:11:42.898+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-26T10:11:46.613+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
