[2023-10-27T14:09:11.710+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrap_scryptopanic.run_selenium scheduled__2023-10-26T10:05:33.116795+00:00 [queued]>
[2023-10-27T14:09:11.771+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrap_scryptopanic.run_selenium scheduled__2023-10-26T10:05:33.116795+00:00 [queued]>
[2023-10-27T14:09:11.773+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-10-27T14:09:11.838+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_selenium> on 2023-10-26 10:05:33.116795+00:00
[2023-10-27T14:09:11.852+0000] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: scrap_scryptopanic.run_selenium scheduled__2023-10-26T10:05:33.116795+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2023-10-27T14:09:11.884+0000] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: scrap_scryptopanic.run_selenium scheduled__2023-10-26T10:05:33.116795+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2023-10-27T14:09:11.893+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
[2023-10-27T14:09:11.942+0000] {standard_task_runner.py:57} INFO - Started process 67 to run task
[2023-10-27T14:09:12.068+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'scrap_scryptopanic', 'run_selenium', 'scheduled__2023-10-26T10:05:33.116795+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/scraping/cryptopanic.py', '--cfg-path', '/tmp/tmpldii12q2']
[2023-10-27T14:09:12.101+0000] {standard_task_runner.py:85} INFO - Job 73: Subtask run_selenium
[2023-10-27T14:09:12.430+0000] {task_command.py:416} INFO - Running <TaskInstance: scrap_scryptopanic.run_selenium scheduled__2023-10-26T10:05:33.116795+00:00 [running]> on host 7b871cd064f6
[2023-10-27T14:09:12.602+0000] {abstractoperator.py:709} ERROR - Exception rendering Jinja template for task 'run_selenium', field 'bash_command'. Template: './start.sh'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 152, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:09:12.612+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1647, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2285, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1243, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 152, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:09:12.648+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=scrap_scryptopanic, task_id=run_selenium, execution_date=20231026T100533, start_date=20231027T140911, end_date=20231027T140912
[2023-10-27T14:09:12.692+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 73 for task run_selenium (./start.sh; 67)
[2023-10-27T14:09:12.730+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-27T14:09:12.869+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
