[2023-10-30T17:52:00.672+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrap_scryptopanic.run_selenium scheduled__2023-10-30T17:46:55.464102+00:00 [queued]>
[2023-10-30T17:52:00.679+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrap_scryptopanic.run_selenium scheduled__2023-10-30T17:46:55.464102+00:00 [queued]>
[2023-10-30T17:52:00.680+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-30T17:52:00.688+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_selenium> on 2023-10-30 17:46:55.464102+00:00
[2023-10-30T17:52:00.704+0000] {standard_task_runner.py:57} INFO - Started process 332 to run task
[2023-10-30T17:52:00.709+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'scrap_scryptopanic', 'run_selenium', 'scheduled__2023-10-30T17:46:55.464102+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/scraping/cryptopanic.py', '--cfg-path', '/tmp/tmplebnr3zv']
[2023-10-30T17:52:00.713+0000] {standard_task_runner.py:85} INFO - Job 147: Subtask run_selenium
[2023-10-30T17:52:00.748+0000] {task_command.py:416} INFO - Running <TaskInstance: scrap_scryptopanic.run_selenium scheduled__2023-10-30T17:46:55.464102+00:00 [running]> on host e2b362512d98
[2023-10-30T17:52:00.774+0000] {abstractoperator.py:709} ERROR - Exception rendering Jinja template for task 'run_selenium', field 'bash_command'. Template: './start.sh'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 152, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-30T17:52:00.776+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1647, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2285, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1243, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 152, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-30T17:52:00.782+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=scrap_scryptopanic, task_id=run_selenium, execution_date=20231030T174655, start_date=20231030T175200, end_date=20231030T175200
[2023-10-30T17:52:00.788+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 147 for task run_selenium (./start.sh; 332)
[2023-10-30T17:52:00.811+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-30T17:52:00.826+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
